import os

BOT_TOKEN = os.getenv("BOT_TOKEN", "")
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "fallback")

WELCOME_BONUS_KOBO = 10000
PREMIUM_COST_KOBO = 5000
VAT_RATE = 0.075
CREATOR_SPLIT = 0.60
